serenity.project.name=BidMart Auth Service Functional Tests
serenity.outputDirectory=build/site/serenity
serenity.requirement.types=feature,story
report.customfields.Application=BidMart Auth Service
report.customfields.Module=Authentication and Access Control
report.customfields.Test Type=Functional and Integration
